[server]
  addr = ":8080"

[direktiv]
  url = "https://example.direktiv.io"
  namespace = "example"
  authToken = "eyEXAMPLETOKENFOOBAR..."

[event]
  source = "dell/unity"
  type = "dell.unity.alert"