smtp:
  address: 0.0.0.0
  port: 2525
  insecureSkipVerify: true
direktiv:
  endpoint: http://192.168.0.115/api/namespaces/direktiv/event
#  endpoint: https://dev.local/api/namespaces/trentis/event
#  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0b2tlbi1jOGUyYjE1MC03YzVjLTRjOTUtODA0MS00NGYwOTFhNjI3NjciLCJncm91cHMiOlsidG9rZW4tYzhlMmIxNTAtN2M1Yy00Yzk1LTgwNDEtNDRmMDkxYTYyNzY3Il0sImV4cCI6MTYyNzg4MjYzMiwiaXNzIjoiZGlyZWt0aXYifQ.msjYEfYXeWxOXZe45IH4dBaAlCZPUqfh0kI-DZ7Tru0
internal: vorteil.io
